* Improving the ClassicalGSG Method: Prediction of logP Using Reduced Moleuclar Feature Spaces

This project builds off a method called ~ClassicalGSG~
and has introduced by the Michigan State University Dickson Lab in [[https://github.com/ADicksonLab/ClassicalGSG][ClassicalGSG: Prediction of logP Using Classical
Molecular Force Fields and Geometric Scattering for Graphs]].  The goal of this project is to decrease the size of the feature space and study how the model behaves. This is a template of the code that was used in this project.

There are seven datasets that that was used in this project: FDA, Huuskonen, NonStar, Star, openchem, SAMPL6, and SAMPL7. The method used to reduce the size of the feature space is [[https://jakevdp.github.io/PythonDataScienceHandbook/05.09-principal-component-analysis.html][principal component analysis (PCA)]]




* Installation

You will need to download this repository. So navigate to where you want this repo to go on your computer and type:

#+begin_src sh
  git clone https://github.com/kyrarivest/ACRES_REU_Project_2021.git
#+end_src

You will also need to install a couple packages if you do not already have them:

#+begin_src sh
  conda install -c pytorch pytorch
  conda install -c scikit-learn
  conda install -c matplotlib
#+end_src

You can also check to see if you have them installed:

#+begin_src sh
  conda list | grep scikit-learn
  conda list | grep pytorch
  conda list | grep matplotlib
#+end_src



* Usage

You will first need to prepare the data to train thee neural network model. You need to decide which datasete you want to train on and how many PCA components to use. Once you know this, navigate to the prepare_data.sb file under ClassicalGSG/examples/prepare_data.sb:

#+BEGIN_SRC bash
 python -m LogpPredictor_CGenFF [molecule.mol2] [molecule.str]
#+END_SRC

To use our MMFF94 ClassicalGSG logP predictor model run the following command:

#+BEGIN_SRC bash
 python -m LogpPredictor_MMFF94  ['smiles']
#+END_SRC

You can generate CGenFF parameter files for your molecule using [[https://cgenff.umaryland.edu][CGenFF]]
online server.

* Dataset
The logP dataset can be downloaded from [[https://doi.org/10.5281/zenodo.4531015][Zenodo]].
Zenodo DOI: 10.5281/zenodo.4531015
