* Improving the ClassicalGSG Method: Prediction of logP Using Reduced Moleuclar Feature Spaces

This project builds off a method called ~ClassicalGSG~
and has introduced by the Michigan State University Dickson Lab in [[https://github.com/ADicksonLab/ClassicalGSG][ClassicalGSG: Prediction of logP Using Classical
Molecular Force Fields and Geometric Scattering for Graphs]].  The goal of this project is to decrease the size of the feature space and study how the model behaves. This is a template of the code that was used in this project.

There are seven datasets that that was used in this project: FDA, Huuskonen, NonStar, Star, openchem, SAMPL6, and SAMPL7. The method used to reduce the size of the feature space is [[https://jakevdp.github.io/PythonDataScienceHandbook/05.09-principal-component-analysis.html][principal component analysis]]




* Installation

You will need to download this repository. So navigate to where you want this repo to go on your computer and type:

#+begin_src sh
  git clone 
  conda activate myenv
#+end_src

Currently you must manually install some of the dependencies using
conda. Do this first:

#+begin_src sh
  conda install -c pytorch pytorch
  conda install -c conda-forge openbabel rdkit
#+end_src


To install from pip:

#+BEGIN_SRC bash
  pip install classicalgsg
#+END_SRC


You can install from the git repo as well:

#+begin_src sh
pip install git+https://github.com/ADicksonLab/ClassicalGSG.git
#+end_src

# TODO: inform about customizing pytorch installation

* Usage

To use our CGenFF ClassicalGSG logP predictor model run the following command:

#+BEGIN_SRC bash
 python -m LogpPredictor_CGenFF [molecule.mol2] [molecule.str]
#+END_SRC

To use our MMFF94 ClassicalGSG logP predictor model run the following command:

#+BEGIN_SRC bash
 python -m LogpPredictor_MMFF94  ['smiles']
#+END_SRC

You can generate CGenFF parameter files for your molecule using [[https://cgenff.umaryland.edu][CGenFF]]
online server.

* Dataset
The logP dataset can be downloaded from [[https://doi.org/10.5281/zenodo.4531015][Zenodo]].
Zenodo DOI: 10.5281/zenodo.4531015
